name: Build and Update GitOps Config

on:
  push:
    branches: [ main ]

jobs:
  build-and-update:
    name: Build Image and Update Config Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      # In a real pipeline this step would build and push a Docker image.
      # For this lab we simulate it by using the commit SHA as the tag.
      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Checkout GitOps config repo
        uses: actions/checkout@v4
        with:
          repository: alytics-bolaji/paystream-gitops
          token: ${{ secrets.GITOPS_PAT }}
          path: gitops-config

      - name: Update image tag in config repo
        run: |
          cd gitops-config
          sed -i "s|newTag:.*|newTag: ${{ env.IMAGE_TAG }}|" \
            apps/paystream/overlays/production/kustomization.yaml
          git config user.email 'ci@paystream.io'
          git config user.name 'CI Bot'
          git add .
          git diff --staged --quiet || git commit -m \
            'chore: update paystream image to ${{ env.IMAGE_TAG }}'
          git push
